env: dev

server:
  host: notes_api
  port: :4040
  shutdown: 5

db:
  username: postgres
  host: notes_db
  port: :5432
  dbType: notes
  reload: false
  version: 1

grpcServer:
  host: notes_api
  port: :4041

kafka:
  brokers: 
    - kafka:4042
  topic: notes.sent.event
  partitions: 1
  replication: 1
  group: sender-1


bot:
  host: api.telegram.org