env: dev

server:
  host: 0.0.0.0
  port: :4040
  shutdown: 5

db:
  username: postgres
  host: notes_db
  port: :5432
  dbType: notes
  reload: false
  version: 1

grpcServer:
  host: 0.0.0.0
  port: :4041

kafka:
  host: 0.0.0.0
  port: :4042
  topic: notes
  partitions: 1


bot:
  host: api.telegram.org

