env: local

server:
  host: 0.0.0.0
  port: :3052
  shutdown: 5

db:
  username: postgres
  password: qwerty
  host: 0.0.0.0
  port: :5432
  dbType: postgres
  reload: false
  version: 1

grpcServer:
  host: 0.0.0.0
  port: :3054

kafka:
  host: 0.0.0.0
  port: :3055
  topic: notes
  partitions: 1

bot:
  host: api.telegram.org